apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit
  namespace: {{ .Values.namespace }}
  labels:
    app: fluentbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
        - name: fluentbit
          image: fluent/fluent-bit
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: configdata-fluent
            mountPath: /fluent-bit/etc/
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            readOnly: true
            mountPath: /var/lib/docker/containers
          env:
          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            value: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
      volumes:
      - name: configdata-fluent
        configMap:
          name: fluent-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

