version: '3'
services:

  myapp:
    container_name: myapp
    build: myapp
    image: myapp
    
  config:
    container_name: configmanager
    build: configmanager
    image: configmanager
    volumes:
      - configvolume:/data/blocklist

  proxy:
    container_name: proxy
    build: proxy
    image: proxy
    ports:
    - "8000:8000"
    depends_on:
    - myapp
    - clone

  clone:
    container_name: clone
    build: clone
    image: clone


volumes:
  configvolume: {}