kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-crb
subjects:
  - kind: ServiceAccount
    name: deployment-manager-sa
    namespace: controlpanel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-manager-cr