apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: controlpanel-front-apirule
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-front
spec:
  host: controlpanel-front
  service:
    name: controlpanel-front-service
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: allow
      mutators: []
