apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-front
  namespace: {{ .Values.namespace }}
  labels:
    app: controlpanel-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: controlpanel-front
  template:
    metadata:
      labels:
        app: controlpanel-front
    spec:
      imagePullSecrets: #To remove
      - name: artifactory-creds
      containers:
        - name: controlpanel-front
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
            - name: CONTROLPANEL_API_URL
              value: {{ .Values.controlpanel_api_url }}
