apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: {{ .Values.namespace }}
  labels:
    app: myapp  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: myapp
