apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: myapp-apirule
  namespace: {{ .Values.namespace }}
  labels:
    app: myapp
spec:
  hosts: 
    - myapp
  service:
    name: myapp-service
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /*
      methods: ["GET","POST"]
      noAuth: true
