apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}-clone-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentName }}-clone  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 2000
  selector:
    app: {{ .Values.deploymentName }}-clone
