apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-manager
  namespace: {{ .Values.namespace }}
  labels:
    app: deployment-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deployment-manager
  template:
    metadata:
      labels:
        app: deployment-manager
    spec:
      containers:
        - name: deployment-manager
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
