apiVersion: v1
kind: Service
metadata:
  name: deployment-manager-service
  namespace: {{ .Values.namespace }}
  labels:
    app: deployment-manager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: deployment-manager
