kind: Service
apiVersion: v1
metadata:
  name: controlpanel-api-service
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: controlpanel-api-service.controlpanel.svc.cluster.local
  ports:
  - port: 80