apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  namespace: {{.Values.namespace}}
spec:
  template:
    metadata:
      name: init-job
    spec:
      # imagePullSecrets:
      # - name: artifactory-creds
      restartPolicy: Never
      containers:
      - name: init-container
        image: {{.Values.initimage}}
        command: ["sh", "-c", "cp /sundew.wasm /data/"]
        imagePullPolicy: Always
        volumeMounts:
        - name: wasm
          mountPath: /data
      volumes:
      - name: wasm
        persistentVolumeClaim:
          claimName: wasm-data
