{{- $secret := lookup "v1" "Secret" .Values.global.namespace "keycloak-db-secrets" }}
{{- $user := "" }}
{{- $password := "" }}
{{- if $secret }}
  {{- $user     = index $secret.data "POSTGRES_USER"     | b64dec }}
  {{- $password = index $secret.data "POSTGRES_PASSWORD" | b64dec }}
{{- else }}
  {{- if or (not .Values.db_user) (eq .Values.db_user "<DB_USER>") }}
    {{- $user = randAlphaNum 10 }}
  {{- else }}
    {{- $user = .Values.db_user }}
  {{- end }}
  {{- if or (not .Values.db_password) (eq .Values.db_password "<DB_PASSWORD>") }}
    {{- $password = randAlphaNum 32 }}
  {{- else }}
    {{- $password = .Values.db_password }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secrets
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRES_USER:     {{ $user     | b64enc }}
  POSTGRES_PASSWORD: {{ $password | b64enc }}
