apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.global.namespace }}
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ if eq .Values.kc_username "<KC_USER>" }}{{ "sQ4LpXvTzB" | b64enc }}{{ else }}{{ .Values.kc_username | b64enc }}{{ end }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ if eq .Values.kc_password "<KC_PASSWORD>" }}{{ "rM2yXnV6qSw9ZpJtL1oCk8FbUe3GsWmDhT" | b64enc }}{{ else }}{{ .Values.kc_password | b64enc }}{{ end }}
