apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: keycloak-db
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.db_port }}
      protocol: TCP
      targetPort: 5432
  selector:
    app: keycloak-db