{{- $secret := lookup "v1" "Secret" .Values.global.namespace "keycloak-secrets" }}
{{- $username := "" }}
{{- $password := "" }}
{{- if $secret }}
  {{- $username = index $secret.data "KC_BOOTSTRAP_ADMIN_USERNAME" | b64dec }}
  {{- $password = index $secret.data "KC_BOOTSTRAP_ADMIN_PASSWORD" | b64dec }}
{{- else }}
  {{- if or (not .Values.kc_username) (eq .Values.kc_username "<KC_USER>") }}
    {{- $username = randAlphaNum 10 }}
  {{- else }}
    {{- $username = .Values.kc_username }}
  {{- end }}
  {{- if or (not .Values.kc_password) (eq .Values.kc_password "<KC_PASSWORD>") }}
    {{- $password = randAlphaNum 32 }}
  {{- else }}
    {{- $password = .Values.kc_password }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.global.namespace }}
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ $username | b64enc }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ $password | b64enc }}
