apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secrets
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRES_USER: {{ if eq .Values.db_user "<DB_USER>" }}{{ "Kp8XsYwLqR" | b64enc }}{{ else }}{{ .Values.db_user | b64enc }}{{ end }}
  POSTGRES_PASSWORD: {{ if eq .Values.db_password "<DB_PASSWORD>" }}{{ "Vb7QnT2zLp5WcJx1Ru9GmSa4YvHk0EoFUiM" | b64enc }}{{ else }}{{ .Values.db_password | b64enc }}{{ end }}
