apiVersion: v1
kind: Service
metadata:
  name: exhaust-service
  namespace: {{ .Values.namespace }}
  labels:
    app: exhaust  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: exhaust
