apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}-exhaust
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deploymentName }}-exhaust
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}-exhaust
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}-exhaust
    spec:
      containers:
        - name: {{ .Values.deploymentName }}-exhaust
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 20m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
          ports:
          - containerPort: 4000
