# Default values for sundew.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: "controlpanel" # Please do not change this value
  db_user: <DB_USER>
  db_password: <DB_PASSWORD>
  db_port: 5432
  db_host: controlpanel-db-service
  kyma_domain: <KYMA_DOMAIN> # e.g. c-28e44bf.kyma.ondemand.com
  keycloak_url: "https://keycloak"
  front_url: "https://controlpanel-front"

controlpanel_api:
  image: "ghcr.io/sap/controlpanel-api:latest"
  deployment_manager_url: "http://deployment-manager-service"
  deploymentmanager_db_password: <DEPLOYMENTMANAGER_DB_PASSWORD>

controlpanel_front:
  image: "ghcr.io/sap/controlpanel-frontend:latest"
  controlpanel_api_url: https://controlpanel-api

deployment-manager:
  image: "ghcr.io/sap/deployment-manager:latest"

keycloak:
  db_host: keycloak-db-service
  db_user: <DB_USER>
  db_password: <DB_PASSWORD>
  db_port: 5432
  kc_username: <KC_USER>
  kc_password: <KC_PASSWORD>
  image: "ghcr.io/sap/keycloak-controlpanel:latest"
