apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
   loki-datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: "http://loki:3100"
        version: 1
        isDefault: false
        jsonData: {}