apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: custom-controlpanel
  namespace: {{ .Values.namespace }}
spec:
   input:
      application:
         containers:
            include:
            - istio-proxy
   output:
      custom: |
         name    http
         host    controlpanel-api-service.controlpanel.svc.cluster.local
         uri     /logs
         format  json
   filters:
      - custom: |
         Name    grep
         Regex   log \b(type\"\s*:\s*\"(alert|event|system|debug))\b
      - custom: |
         Name            nest
         Operation       lift
         Nested_under    kubernetes
         Add_prefix      kubernetes.
      - custom: |
         Name            nest
         Operation       lift
         Nested_under    kubernetes.labels
         Add_prefix      kubernetes.labels.
      - custom: |
         Name modify
         Hard_copy kubernetes.namespace_name namespace
         Hard_copy kubernetes.labels.app application
      - custom: |
         Name            nest
         Operation       nest
         Wildcard        kubernetes.*
         Nest_under      kubernetes.labels
         Remove_prefix   kubernetes.labels.
      - custom: |
         Name            nest
         Operation       nest
         Wildcard        kubernetes.*
         Nest_under      kubernetes
         Remove_prefix   kubernetes.
      - custom: |
         Name modify
         Remove kubernetes