apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: sample
spec:
  input:
    application:
      namespaces:
        include:
        - {{ .Values.appnamespace }}
  output:
    http:
      dedot: true
      host:
        value: log-sink.{{ .Values.namespace }}.svc.cluster.local
      port: "9880"
      uri: /
      format: json
      tls:
        disabled: true
        skipCertificateValidation: true