apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-sink
  namespace: {{ .Values.namespace }}
  labels:
    test: fluent-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-sink
  template:
    metadata:
      labels:
        app: log-sink
      name: log-sink
    spec:
      containers:
        - args:
            - -i http
            - -o stdout
            - -q
          image: fluent/fluent-bit:latest
          livenessProbe:
            tcpSocket:
              port: http-ingest
          name: log-sink
          ports:
            - containerPort: 9880
              name: http-ingest
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http-ingest
---
apiVersion: v1
kind: Service
metadata:
  name: log-sink
  namespace: {{ .Values.namespace }}
  labels:
    test: fluent-pipeline
spec:
  ports:
    - name: http-ingest
      port: 9880
      protocol: TCP
      targetPort: http-ingest
  selector:
    app: log-sink