apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
patches:
  - path: envoy-patch.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: EnvoyFilter
      name: test-myapp-cloudactivedefensefilter #EDIT THIS VALUE
