apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controlpanel-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
