apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-api
spec:
  selector:
    matchLabels:
      app: controlpanel-api
  template:
    metadata:
      labels:
        app: controlpanel-api
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v controlpanel-db-service 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: controlpanel-api
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:
            - name: DB_PORT
              value: {{ .Values.global.db_port | quote }}
            - name: DB_HOST
              value: {{ .Values.global.db_host }}
            - name: CONTROLPANEL_FRONTEND_URL
              value: {{ printf "%s.%s" .Values.global.front_url (trimPrefix "." .Values.global.kyma_domain) }}
            - name: DEPLOYMENT_MANAGER_URL
              value: {{ .Values.deployment_manager_url }}
            - name: KEYCLOAK_URL
              value: {{ printf "%s.%s" .Values.global.keycloak_url (trimPrefix "." .Values.global.kyma_domain) }}
          envFrom:
            - secretRef:
                name: controlpanel-db-secrets
            - secretRef:
                name: deployment-manager-db-secrets
