apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: controlpanel-api-apirule
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-api
spec:
  host: controlpanel-api
  service:
    name: controlpanel-api-service
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE"]
      accessStrategies:
        - handler: allow
      mutators: []
