apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-api
spec:
  selector:
    matchLabels:
      app: controlpanel-api
  template:
    metadata:
      labels:
        app: controlpanel-api
        sidecar.istio.io/inject: 'true'
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:16-alpine
        command: ['sh', '-c', 'until pg_isready -h controlpanel-db-service -p 5432 -U $(POSTGRES_USER); do echo waiting for db; sleep 2; done']
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: controlpanel-db-secrets
                key: POSTGRES_USER
      containers:
        - name: controlpanel-api
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:
            - name: DB_PORT
              value: {{ .Values.global.db_port | quote }}
            - name: DB_HOST
              value: {{ .Values.global.db_host }}
            - name: CONTROLPANEL_FRONTEND_URL
              value: {{ printf "%s.%s" .Values.global.front_url (trimPrefix "." .Values.global.kyma_domain) }}
            - name: DEPLOYMENT_MANAGER_URL
              value: {{ .Values.deployment_manager_url }}
            - name: KEYCLOAK_URL
              value: {{ printf "%s.%s" .Values.global.keycloak_url (trimPrefix "." .Values.global.kyma_domain) }}
          envFrom:
            - secretRef:
                name: controlpanel-db-secrets
            - secretRef:
                name: deployment-manager-db-secrets
