apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: controlpanel-api-apirule
  namespace: {{ .Values.global.namespace }}
  labels:
    app: controlpanel-api
spec:
  hosts: 
    - controlpanel-api
  service:
    name: controlpanel-api-service
    port: 80
  gateway: kyma-system/kyma-gateway
  corsPolicy:
    allowOrigins:
      - prefix: {{ printf "%s.%s" .Values.global.front_url (trimPrefix "." .Values.global.kyma_domain) }}
    allowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowHeaders:
      - Authorization
      - Content-Type
    exposeHeaders:
      - Content-Type
    allowCredentials: true
  rules:
    - path: /*
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
      noAuth: true