apiVersion: v1
kind: Secret
metadata:
  name: controlpanel-db-secrets
  namespace: {{ .Values.global.namespace }}
data:
  POSTGRES_USER: {{ if eq .Values.global.db_user "<DB_USER>" }}{{ "dh7RmNkWoZ" | b64enc }}{{ else }}{{ .Values.global.db_user | b64enc }}{{ end }}
  POSTGRES_PASSWORD: {{ if eq .Values.global.db_password "<DB_PASSWORD>" }}{{ "8fjG3PWaQeT97lUDuAVxY0Kbz5HJn4Rc" | b64enc }}{{ else }}{{ .Values.global.db_password | b64enc }}{{ end }}
