{{- $secret := lookup "v1" "Secret" .Values.global.namespace "deployment-manager-db-secrets" }}
{{- $password := "" }}
{{- if $secret }}
  {{- $password = index $secret.data "DEPLOYMENT_MANAGER_PASSWORD" | b64dec }}
{{- else }}
  {{- if or (not .Values.deploymentmanager_db_password) (eq .Values.deploymentmanager_db_password "<DEPLOYMENTMANAGER_DB_PASSWORD>") }}
    {{- $password = randAlphaNum 32 }}
  {{- else }}
    {{- $password = .Values.deploymentmanager_db_password }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: deployment-manager-db-secrets
  namespace: {{ .Values.global.namespace }}
data:
  DEPLOYMENT_MANAGER_PASSWORD: {{ $password | b64enc }}