apiVersion: v1
kind: Secret
metadata:
  name: deployment-manager-db-secrets
  namespace: {{ .Values.global.namespace }}
data:
  DEPLOYMENT_MANAGER_PASSWORD: {{ if eq .Values.deploymentmanager_db_password "<DEPLOYMENTMANAGER_DB_PASSWORD>" }}{{ "B4mnQYsT8zPj6FaKxtD7rV9bL5Xg2NHW" | b64enc }}{{ else }}{{ .Values.deploymentmanager_db_password | b64enc }}{{ end }}