apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: keycloak-to-controlpanel-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: controlpanel-api
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.global.namespace }}/sa/keycloak-sa
      to:
        - operation:
            methods: ["POST"]
            paths: ["/customer"]
