apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: telemetry-to-controlpanel-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: controlpanel-api
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kyma-system/sa/telemetry-fluent-bit
      to:
        - operation:
            methods: ["POST"]
            paths: ["/logs"]
