apiVersion: v1
kind: Service
metadata:
  name: configmanager-service
  namespace: config-ns
  labels:
    app: configmanager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: configmanager
