apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: configmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmanager
  template:
    metadata:
      labels:
        app: configmanager
    spec:
      # imagePullSecrets:
      # - name: artifactory-creds
      containers:
        - name: configmanager
          image: {{.Values.configimage}}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 20m
              memory: 32Mi
            requests:
              cpu: 10m
              memory: 16Mi
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: config
            mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-data
      securityContext:
        fsGroup: 1234

