name: Run envoy proxy tests

on: [push]

permissions:
  contents: read
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set execute permissions for the test script
        run: chmod +x ./runTests.sh

      - name: Run a script
        run: |
          OUTPUT=$(./runTests.sh)
          echo "$OUTPUT"
          
          if echo "$OUTPUT" | grep -q 'FAIL'; then
            echo -e "\033[0;31mTEST FAILED\033[0m"
            echo One or more tests failed !
            exit 1
          else
            echo -e "\033[0;32mTEST PASSED\033[0m"
            echo All tests passed !
            exit 0
          fi
