apiVersion: v1
kind: Secret
metadata:
  name: controlpanel-db-secrets
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.controlpanel.db_user | b64enc }}
  POSTGRES_PASSWORD: {{  .Values.controlpanel.db_password | b64enc }}