apiVersion: apps/v1
kind: Deployment
metadata:
  name: controlpanel-api
  namespace: {{ .Values.namespace }}
  labels:
    app: controlpanel-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: controlpanel-api
  template:
    metadata:
      labels:
        app: controlpanel-api
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v controlpanel-db-service 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: controlpanel-api
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8050
          env:
            - name: DB_PORT
              value: {{ .Values.db_port | quote }}
            - name: DB_HOST
              value: {{ .Values.db_host }}
            - name: CONTROLPANEL_FRONTEND_URL
              value: {{ .Values.controlpanel_front_url }}
          envFrom:
            - secretRef:
                name: controlpanel-db-secrets
