{{- if not .Values.from_wizard }}
apiVersion: v1
kind: Secret
metadata:
  name: controlpanel-db-secrets
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: <B64_DB_USER>
  POSTGRES_PASSWORD: <B64_DB_PASSWORD>
{{- end }}