{{- if not .Values.from_wizard }}
apiVersion: v1
kind: Secret
metadata:
  name: controlpanel-db-secrets
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.db_user | b64enc }}
  POSTGRES_PASSWORD: {{  .Values.db_password | b64enc }}
{{- end }}