apiVersion: v1
kind: Service
metadata:
  name: controlpanel-db-service
  namespace: {{ .Values.namespace }}
  labels:
    app: controlpanel-db
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: controlpanel-db