apiVersion: v1
kind: Service
metadata:
  name: controlpanel-api-service
  namespace: {{ .Values.namespace }}
  labels:
    app: controlpanel-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8050
  selector:
    app: controlpanel-api
